// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_make_duplicate 22
#define SYS_simplearith 23
#define SYS_show_process_family 24
#define SYS_set_priority_syscall 25
#define SYS_grep_syscall 26
#define SYS_start_throughput_measuring 27
#define SYS_end_throughput_measuring 28
#define SYS_print_process_info 29
#define SYS_plock_acquire 30
#define SYS_plock_release 31
#define SYS_rwlock_test  32
#define SYS_test_acquire 33
#define SYS_test_release 34
#define SYS_getlockstat 35
#define SYS_rwlock_read_acquire   36
#define SYS_rwlock_read_release   37
#define SYS_rwlock_write_acquire  38
#define SYS_rwlock_write_release  39
#define SYS_write_page  40
#define SYS_read_page   41
#define SYS_print_stats 42